### ISSUE TITLE
Cannot find module 'task-queue/task-queue'

### ISSUE THREAD

**Issue by jmwright** [jaridmargolin/rc-socket.js#19]
Trying rc-socket.js out on Node (installing via `npm install rc-socket.js --save`, and got the following error.

```
Cannot find module 'task-queue/task-queue'
```

I installed and required task-queue, but still get the error.

**Comment by davidtsuji** [comment]
As a workaround I changed the import path.

was

`import Socket from 'rc-socket.js'`

changed to

`import Socket from 'rc-socket.js/dist/rc-socket'`

**Comment by jaridmargolin** [comment]
Hey ya'll. Sorry about the radio silence. Have released v3.0.0. It should fix import issues.

* warning: v3.0.0 is currently intended to support evergreen browsers.
